# Generated by Django 5.0 on 2023-12-19 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=500, null=True, verbose_name='Etiket')),
                ('name', models.CharField(max_length=500, verbose_name='Adı')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Konum')),
                ('status', models.CharField(blank=True, max_length=500, null=True, verbose_name='Durum')),
                ('manufacturer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Üretici')),
                ('brand', models.CharField(blank=True, max_length=500, null=True, verbose_name='Marka')),
                ('model', models.CharField(blank=True, max_length=500, null=True, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=500, null=True, verbose_name='Seri Numarası')),
                ('product_number', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ürün Numarası')),
                ('inventory_number', models.CharField(blank=True, max_length=500, null=True, verbose_name='Stok Numarası')),
                ('used_by', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kullanan Birim / Kullanıcı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Not')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarih/Saat')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarih/Saat')),
            ],
            options={
                'verbose_name': 'Ürün / Cihaz',
                'verbose_name_plural': 'Ürünler / Cihazlar',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementation', models.TextField(verbose_name='Yapılan İşlem')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar (₺)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Not')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarih/Saat')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarih/Saat')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.entity', verbose_name='Ürün / Cihaz')),
            ],
            options={
                'verbose_name': 'Yapılan İşlem',
                'verbose_name_plural': 'Yapılan İşlemler',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Tarih / Saat')),
                ('customer', models.CharField(max_length=500, verbose_name='Müşteri / Firma Bilgileri')),
                ('phone1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Telefon-1')),
                ('phone2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Telefon-2')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Değiştirilme Tarih/Saat')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarih/Saat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Düzenleyen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Servis Kaydı',
                'verbose_name_plural': 'Servis Kayıtları',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='Servis Kaydı'),
        ),
    ]
