# Generated by Django 5.1.3 on 2025-01-02 07:11

from django.db import migrations
from django.conf import settings
from django.contrib.auth import get_user_model


def create_super_user(apps, schema_editor):
    user = get_user_model()
    if not user.objects.filter(username=settings.DJANGO_SUPERUSER_USERNAME, email=settings.DJANGO_SUPERUSER_EMAIL).exists():
        admin = user.objects.create_superuser(
           username=settings.DJANGO_SUPERUSER_USERNAME, password=settings.DJANGO_SUPERUSER_PASSWORD, email=settings.DJANGO_SUPERUSER_EMAIL
        )
        admin.save()
    else:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_super_user),
    ]
